// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/activitylog"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/board"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
)

// ActivityLog is the model entity for the ActivityLog schema.
type ActivityLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType string `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID *uuid.UUID `json:"entity_id,omitempty"`
	// OldValue holds the value of the "old_value" field.
	OldValue map[string]interface{} `json:"old_value,omitempty"`
	// NewValue holds the value of the "new_value" field.
	NewValue map[string]interface{} `json:"new_value,omitempty"`
	// BoardID holds the value of the "board_id" field.
	BoardID uuid.UUID `json:"board_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityLogQuery when eager-loading is set.
	Edges        ActivityLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActivityLogEdges holds the relations/edges for other nodes in the graph.
type ActivityLogEdges struct {
	// Board holds the value of the board edge.
	Board *Board `json:"board,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BoardOrErr returns the Board value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityLogEdges) BoardOrErr() (*Board, error) {
	if e.Board != nil {
		return e.Board, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: board.Label}
	}
	return nil, &NotLoadedError{edge: "board"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldEntityID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case activitylog.FieldOldValue, activitylog.FieldNewValue:
			values[i] = new([]byte)
		case activitylog.FieldAction, activitylog.FieldEntityType:
			values[i] = new(sql.NullString)
		case activitylog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case activitylog.FieldID, activitylog.FieldBoardID, activitylog.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityLog fields.
func (al *ActivityLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				al.ID = *value
			}
		case activitylog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				al.Action = value.String
			}
		case activitylog.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				al.EntityType = value.String
			}
		case activitylog.FieldEntityID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				al.EntityID = new(uuid.UUID)
				*al.EntityID = *value.S.(*uuid.UUID)
			}
		case activitylog.FieldOldValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field old_value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &al.OldValue); err != nil {
					return fmt.Errorf("unmarshal field old_value: %w", err)
				}
			}
		case activitylog.FieldNewValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field new_value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &al.NewValue); err != nil {
					return fmt.Errorf("unmarshal field new_value: %w", err)
				}
			}
		case activitylog.FieldBoardID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field board_id", values[i])
			} else if value != nil {
				al.BoardID = *value
			}
		case activitylog.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				al.UserID = *value
			}
		case activitylog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				al.CreatedAt = value.Time
			}
		default:
			al.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActivityLog.
// This includes values selected through modifiers, order, etc.
func (al *ActivityLog) Value(name string) (ent.Value, error) {
	return al.selectValues.Get(name)
}

// QueryBoard queries the "board" edge of the ActivityLog entity.
func (al *ActivityLog) QueryBoard() *BoardQuery {
	return NewActivityLogClient(al.config).QueryBoard(al)
}

// QueryUser queries the "user" edge of the ActivityLog entity.
func (al *ActivityLog) QueryUser() *UserQuery {
	return NewActivityLogClient(al.config).QueryUser(al)
}

// Update returns a builder for updating this ActivityLog.
// Note that you need to call ActivityLog.Unwrap() before calling this method if this ActivityLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (al *ActivityLog) Update() *ActivityLogUpdateOne {
	return NewActivityLogClient(al.config).UpdateOne(al)
}

// Unwrap unwraps the ActivityLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (al *ActivityLog) Unwrap() *ActivityLog {
	_tx, ok := al.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityLog is not a transactional entity")
	}
	al.config.driver = _tx.drv
	return al
}

// String implements the fmt.Stringer.
func (al *ActivityLog) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", al.ID))
	builder.WriteString("action=")
	builder.WriteString(al.Action)
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(al.EntityType)
	builder.WriteString(", ")
	if v := al.EntityID; v != nil {
		builder.WriteString("entity_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("old_value=")
	builder.WriteString(fmt.Sprintf("%v", al.OldValue))
	builder.WriteString(", ")
	builder.WriteString("new_value=")
	builder.WriteString(fmt.Sprintf("%v", al.NewValue))
	builder.WriteString(", ")
	builder.WriteString("board_id=")
	builder.WriteString(fmt.Sprintf("%v", al.BoardID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", al.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(al.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActivityLogs is a parsable slice of ActivityLog.
type ActivityLogs []*ActivityLog
