// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/activitylog"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/board"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/predicate"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
)

// ActivityLogQuery is the builder for querying ActivityLog entities.
type ActivityLogQuery struct {
	config
	ctx        *QueryContext
	order      []activitylog.OrderOption
	inters     []Interceptor
	predicates []predicate.ActivityLog
	withBoard  *BoardQuery
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ActivityLogQuery builder.
func (alq *ActivityLogQuery) Where(ps ...predicate.ActivityLog) *ActivityLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *ActivityLogQuery) Limit(limit int) *ActivityLogQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *ActivityLogQuery) Offset(offset int) *ActivityLogQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *ActivityLogQuery) Unique(unique bool) *ActivityLogQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *ActivityLogQuery) Order(o ...activitylog.OrderOption) *ActivityLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// QueryBoard chains the current query on the "board" edge.
func (alq *ActivityLogQuery) QueryBoard() *BoardQuery {
	query := (&BoardClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activitylog.Table, activitylog.FieldID, selector),
			sqlgraph.To(board.Table, board.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, activitylog.BoardTable, activitylog.BoardColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (alq *ActivityLogQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activitylog.Table, activitylog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, activitylog.UserTable, activitylog.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ActivityLog entity from the query.
// Returns a *NotFoundError when no ActivityLog was found.
func (alq *ActivityLogQuery) First(ctx context.Context) (*ActivityLog, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{activitylog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *ActivityLogQuery) FirstX(ctx context.Context) *ActivityLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ActivityLog ID from the query.
// Returns a *NotFoundError when no ActivityLog ID was found.
func (alq *ActivityLogQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{activitylog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *ActivityLogQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ActivityLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ActivityLog entity is found.
// Returns a *NotFoundError when no ActivityLog entities are found.
func (alq *ActivityLogQuery) Only(ctx context.Context) (*ActivityLog, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{activitylog.Label}
	default:
		return nil, &NotSingularError{activitylog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *ActivityLogQuery) OnlyX(ctx context.Context) *ActivityLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ActivityLog ID in the query.
// Returns a *NotSingularError when more than one ActivityLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *ActivityLogQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{activitylog.Label}
	default:
		err = &NotSingularError{activitylog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *ActivityLogQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActivityLogs.
func (alq *ActivityLogQuery) All(ctx context.Context) ([]*ActivityLog, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryAll)
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ActivityLog, *ActivityLogQuery]()
	return withInterceptors[[]*ActivityLog](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *ActivityLogQuery) AllX(ctx context.Context) []*ActivityLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ActivityLog IDs.
func (alq *ActivityLogQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryIDs)
	if err = alq.Select(activitylog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *ActivityLogQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *ActivityLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryCount)
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*ActivityLogQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *ActivityLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *ActivityLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryExist)
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *ActivityLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ActivityLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *ActivityLogQuery) Clone() *ActivityLogQuery {
	if alq == nil {
		return nil
	}
	return &ActivityLogQuery{
		config:     alq.config,
		ctx:        alq.ctx.Clone(),
		order:      append([]activitylog.OrderOption{}, alq.order...),
		inters:     append([]Interceptor{}, alq.inters...),
		predicates: append([]predicate.ActivityLog{}, alq.predicates...),
		withBoard:  alq.withBoard.Clone(),
		withUser:   alq.withUser.Clone(),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// WithBoard tells the query-builder to eager-load the nodes that are connected to
// the "board" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *ActivityLogQuery) WithBoard(opts ...func(*BoardQuery)) *ActivityLogQuery {
	query := (&BoardClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withBoard = query
	return alq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *ActivityLogQuery) WithUser(opts ...func(*UserQuery)) *ActivityLogQuery {
	query := (&UserClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withUser = query
	return alq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActivityLog.Query().
//		GroupBy(activitylog.FieldAction).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (alq *ActivityLogQuery) GroupBy(field string, fields ...string) *ActivityLogGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ActivityLogGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = activitylog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//	}
//
//	client.ActivityLog.Query().
//		Select(activitylog.FieldAction).
//		Scan(ctx, &v)
func (alq *ActivityLogQuery) Select(fields ...string) *ActivityLogSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &ActivityLogSelect{ActivityLogQuery: alq}
	sbuild.label = activitylog.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ActivityLogSelect configured with the given aggregations.
func (alq *ActivityLogQuery) Aggregate(fns ...AggregateFunc) *ActivityLogSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *ActivityLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !activitylog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *ActivityLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ActivityLog, error) {
	var (
		nodes       = []*ActivityLog{}
		_spec       = alq.querySpec()
		loadedTypes = [2]bool{
			alq.withBoard != nil,
			alq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ActivityLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ActivityLog{config: alq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := alq.withBoard; query != nil {
		if err := alq.loadBoard(ctx, query, nodes, nil,
			func(n *ActivityLog, e *Board) { n.Edges.Board = e }); err != nil {
			return nil, err
		}
	}
	if query := alq.withUser; query != nil {
		if err := alq.loadUser(ctx, query, nodes, nil,
			func(n *ActivityLog, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (alq *ActivityLogQuery) loadBoard(ctx context.Context, query *BoardQuery, nodes []*ActivityLog, init func(*ActivityLog), assign func(*ActivityLog, *Board)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ActivityLog)
	for i := range nodes {
		fk := nodes[i].BoardID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(board.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "board_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (alq *ActivityLogQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ActivityLog, init func(*ActivityLog), assign func(*ActivityLog, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ActivityLog)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (alq *ActivityLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *ActivityLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(activitylog.Table, activitylog.Columns, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activitylog.FieldID)
		for i := range fields {
			if fields[i] != activitylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if alq.withBoard != nil {
			_spec.Node.AddColumnOnce(activitylog.FieldBoardID)
		}
		if alq.withUser != nil {
			_spec.Node.AddColumnOnce(activitylog.FieldUserID)
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *ActivityLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(activitylog.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = activitylog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ActivityLogGroupBy is the group-by builder for ActivityLog entities.
type ActivityLogGroupBy struct {
	selector
	build *ActivityLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *ActivityLogGroupBy) Aggregate(fns ...AggregateFunc) *ActivityLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *ActivityLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, ent.OpQueryGroupBy)
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActivityLogQuery, *ActivityLogGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *ActivityLogGroupBy) sqlScan(ctx context.Context, root *ActivityLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ActivityLogSelect is the builder for selecting fields of ActivityLog entities.
type ActivityLogSelect struct {
	*ActivityLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *ActivityLogSelect) Aggregate(fns ...AggregateFunc) *ActivityLogSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *ActivityLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, ent.OpQuerySelect)
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActivityLogQuery, *ActivityLogSelect](ctx, als.ActivityLogQuery, als, als.inters, v)
}

func (als *ActivityLogSelect) sqlScan(ctx context.Context, root *ActivityLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
