// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/activitylog"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/board"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/predicate"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
)

// ActivityLogUpdate is the builder for updating ActivityLog entities.
type ActivityLogUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityLogMutation
}

// Where appends a list predicates to the ActivityLogUpdate builder.
func (alu *ActivityLogUpdate) Where(ps ...predicate.ActivityLog) *ActivityLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetAction sets the "action" field.
func (alu *ActivityLogUpdate) SetAction(s string) *ActivityLogUpdate {
	alu.mutation.SetAction(s)
	return alu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (alu *ActivityLogUpdate) SetNillableAction(s *string) *ActivityLogUpdate {
	if s != nil {
		alu.SetAction(*s)
	}
	return alu
}

// SetEntityType sets the "entity_type" field.
func (alu *ActivityLogUpdate) SetEntityType(s string) *ActivityLogUpdate {
	alu.mutation.SetEntityType(s)
	return alu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (alu *ActivityLogUpdate) SetNillableEntityType(s *string) *ActivityLogUpdate {
	if s != nil {
		alu.SetEntityType(*s)
	}
	return alu
}

// ClearEntityType clears the value of the "entity_type" field.
func (alu *ActivityLogUpdate) ClearEntityType() *ActivityLogUpdate {
	alu.mutation.ClearEntityType()
	return alu
}

// SetEntityID sets the "entity_id" field.
func (alu *ActivityLogUpdate) SetEntityID(u uuid.UUID) *ActivityLogUpdate {
	alu.mutation.SetEntityID(u)
	return alu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (alu *ActivityLogUpdate) SetNillableEntityID(u *uuid.UUID) *ActivityLogUpdate {
	if u != nil {
		alu.SetEntityID(*u)
	}
	return alu
}

// ClearEntityID clears the value of the "entity_id" field.
func (alu *ActivityLogUpdate) ClearEntityID() *ActivityLogUpdate {
	alu.mutation.ClearEntityID()
	return alu
}

// SetOldValue sets the "old_value" field.
func (alu *ActivityLogUpdate) SetOldValue(m map[string]interface{}) *ActivityLogUpdate {
	alu.mutation.SetOldValue(m)
	return alu
}

// ClearOldValue clears the value of the "old_value" field.
func (alu *ActivityLogUpdate) ClearOldValue() *ActivityLogUpdate {
	alu.mutation.ClearOldValue()
	return alu
}

// SetNewValue sets the "new_value" field.
func (alu *ActivityLogUpdate) SetNewValue(m map[string]interface{}) *ActivityLogUpdate {
	alu.mutation.SetNewValue(m)
	return alu
}

// ClearNewValue clears the value of the "new_value" field.
func (alu *ActivityLogUpdate) ClearNewValue() *ActivityLogUpdate {
	alu.mutation.ClearNewValue()
	return alu
}

// SetBoardID sets the "board_id" field.
func (alu *ActivityLogUpdate) SetBoardID(u uuid.UUID) *ActivityLogUpdate {
	alu.mutation.SetBoardID(u)
	return alu
}

// SetNillableBoardID sets the "board_id" field if the given value is not nil.
func (alu *ActivityLogUpdate) SetNillableBoardID(u *uuid.UUID) *ActivityLogUpdate {
	if u != nil {
		alu.SetBoardID(*u)
	}
	return alu
}

// SetUserID sets the "user_id" field.
func (alu *ActivityLogUpdate) SetUserID(u uuid.UUID) *ActivityLogUpdate {
	alu.mutation.SetUserID(u)
	return alu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (alu *ActivityLogUpdate) SetNillableUserID(u *uuid.UUID) *ActivityLogUpdate {
	if u != nil {
		alu.SetUserID(*u)
	}
	return alu
}

// ClearUserID clears the value of the "user_id" field.
func (alu *ActivityLogUpdate) ClearUserID() *ActivityLogUpdate {
	alu.mutation.ClearUserID()
	return alu
}

// SetBoard sets the "board" edge to the Board entity.
func (alu *ActivityLogUpdate) SetBoard(b *Board) *ActivityLogUpdate {
	return alu.SetBoardID(b.ID)
}

// SetUser sets the "user" edge to the User entity.
func (alu *ActivityLogUpdate) SetUser(u *User) *ActivityLogUpdate {
	return alu.SetUserID(u.ID)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (alu *ActivityLogUpdate) Mutation() *ActivityLogMutation {
	return alu.mutation
}

// ClearBoard clears the "board" edge to the Board entity.
func (alu *ActivityLogUpdate) ClearBoard() *ActivityLogUpdate {
	alu.mutation.ClearBoard()
	return alu
}

// ClearUser clears the "user" edge to the User entity.
func (alu *ActivityLogUpdate) ClearUser() *ActivityLogUpdate {
	alu.mutation.ClearUser()
	return alu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *ActivityLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *ActivityLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *ActivityLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *ActivityLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alu *ActivityLogUpdate) check() error {
	if v, ok := alu.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	if v, ok := alu.mutation.EntityType(); ok {
		if err := activitylog.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.entity_type": %w`, err)}
		}
	}
	if alu.mutation.BoardCleared() && len(alu.mutation.BoardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityLog.board"`)
	}
	return nil
}

func (alu *ActivityLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := alu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitylog.Table, activitylog.Columns, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := alu.mutation.EntityType(); ok {
		_spec.SetField(activitylog.FieldEntityType, field.TypeString, value)
	}
	if alu.mutation.EntityTypeCleared() {
		_spec.ClearField(activitylog.FieldEntityType, field.TypeString)
	}
	if value, ok := alu.mutation.EntityID(); ok {
		_spec.SetField(activitylog.FieldEntityID, field.TypeUUID, value)
	}
	if alu.mutation.EntityIDCleared() {
		_spec.ClearField(activitylog.FieldEntityID, field.TypeUUID)
	}
	if value, ok := alu.mutation.OldValue(); ok {
		_spec.SetField(activitylog.FieldOldValue, field.TypeJSON, value)
	}
	if alu.mutation.OldValueCleared() {
		_spec.ClearField(activitylog.FieldOldValue, field.TypeJSON)
	}
	if value, ok := alu.mutation.NewValue(); ok {
		_spec.SetField(activitylog.FieldNewValue, field.TypeJSON, value)
	}
	if alu.mutation.NewValueCleared() {
		_spec.ClearField(activitylog.FieldNewValue, field.TypeJSON)
	}
	if alu.mutation.BoardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.BoardTable,
			Columns: []string{activitylog.BoardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.BoardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.BoardTable,
			Columns: []string{activitylog.BoardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if alu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// ActivityLogUpdateOne is the builder for updating a single ActivityLog entity.
type ActivityLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityLogMutation
}

// SetAction sets the "action" field.
func (aluo *ActivityLogUpdateOne) SetAction(s string) *ActivityLogUpdateOne {
	aluo.mutation.SetAction(s)
	return aluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (aluo *ActivityLogUpdateOne) SetNillableAction(s *string) *ActivityLogUpdateOne {
	if s != nil {
		aluo.SetAction(*s)
	}
	return aluo
}

// SetEntityType sets the "entity_type" field.
func (aluo *ActivityLogUpdateOne) SetEntityType(s string) *ActivityLogUpdateOne {
	aluo.mutation.SetEntityType(s)
	return aluo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (aluo *ActivityLogUpdateOne) SetNillableEntityType(s *string) *ActivityLogUpdateOne {
	if s != nil {
		aluo.SetEntityType(*s)
	}
	return aluo
}

// ClearEntityType clears the value of the "entity_type" field.
func (aluo *ActivityLogUpdateOne) ClearEntityType() *ActivityLogUpdateOne {
	aluo.mutation.ClearEntityType()
	return aluo
}

// SetEntityID sets the "entity_id" field.
func (aluo *ActivityLogUpdateOne) SetEntityID(u uuid.UUID) *ActivityLogUpdateOne {
	aluo.mutation.SetEntityID(u)
	return aluo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (aluo *ActivityLogUpdateOne) SetNillableEntityID(u *uuid.UUID) *ActivityLogUpdateOne {
	if u != nil {
		aluo.SetEntityID(*u)
	}
	return aluo
}

// ClearEntityID clears the value of the "entity_id" field.
func (aluo *ActivityLogUpdateOne) ClearEntityID() *ActivityLogUpdateOne {
	aluo.mutation.ClearEntityID()
	return aluo
}

// SetOldValue sets the "old_value" field.
func (aluo *ActivityLogUpdateOne) SetOldValue(m map[string]interface{}) *ActivityLogUpdateOne {
	aluo.mutation.SetOldValue(m)
	return aluo
}

// ClearOldValue clears the value of the "old_value" field.
func (aluo *ActivityLogUpdateOne) ClearOldValue() *ActivityLogUpdateOne {
	aluo.mutation.ClearOldValue()
	return aluo
}

// SetNewValue sets the "new_value" field.
func (aluo *ActivityLogUpdateOne) SetNewValue(m map[string]interface{}) *ActivityLogUpdateOne {
	aluo.mutation.SetNewValue(m)
	return aluo
}

// ClearNewValue clears the value of the "new_value" field.
func (aluo *ActivityLogUpdateOne) ClearNewValue() *ActivityLogUpdateOne {
	aluo.mutation.ClearNewValue()
	return aluo
}

// SetBoardID sets the "board_id" field.
func (aluo *ActivityLogUpdateOne) SetBoardID(u uuid.UUID) *ActivityLogUpdateOne {
	aluo.mutation.SetBoardID(u)
	return aluo
}

// SetNillableBoardID sets the "board_id" field if the given value is not nil.
func (aluo *ActivityLogUpdateOne) SetNillableBoardID(u *uuid.UUID) *ActivityLogUpdateOne {
	if u != nil {
		aluo.SetBoardID(*u)
	}
	return aluo
}

// SetUserID sets the "user_id" field.
func (aluo *ActivityLogUpdateOne) SetUserID(u uuid.UUID) *ActivityLogUpdateOne {
	aluo.mutation.SetUserID(u)
	return aluo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aluo *ActivityLogUpdateOne) SetNillableUserID(u *uuid.UUID) *ActivityLogUpdateOne {
	if u != nil {
		aluo.SetUserID(*u)
	}
	return aluo
}

// ClearUserID clears the value of the "user_id" field.
func (aluo *ActivityLogUpdateOne) ClearUserID() *ActivityLogUpdateOne {
	aluo.mutation.ClearUserID()
	return aluo
}

// SetBoard sets the "board" edge to the Board entity.
func (aluo *ActivityLogUpdateOne) SetBoard(b *Board) *ActivityLogUpdateOne {
	return aluo.SetBoardID(b.ID)
}

// SetUser sets the "user" edge to the User entity.
func (aluo *ActivityLogUpdateOne) SetUser(u *User) *ActivityLogUpdateOne {
	return aluo.SetUserID(u.ID)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (aluo *ActivityLogUpdateOne) Mutation() *ActivityLogMutation {
	return aluo.mutation
}

// ClearBoard clears the "board" edge to the Board entity.
func (aluo *ActivityLogUpdateOne) ClearBoard() *ActivityLogUpdateOne {
	aluo.mutation.ClearBoard()
	return aluo
}

// ClearUser clears the "user" edge to the User entity.
func (aluo *ActivityLogUpdateOne) ClearUser() *ActivityLogUpdateOne {
	aluo.mutation.ClearUser()
	return aluo
}

// Where appends a list predicates to the ActivityLogUpdate builder.
func (aluo *ActivityLogUpdateOne) Where(ps ...predicate.ActivityLog) *ActivityLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *ActivityLogUpdateOne) Select(field string, fields ...string) *ActivityLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated ActivityLog entity.
func (aluo *ActivityLogUpdateOne) Save(ctx context.Context) (*ActivityLog, error) {
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *ActivityLogUpdateOne) SaveX(ctx context.Context) *ActivityLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *ActivityLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *ActivityLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aluo *ActivityLogUpdateOne) check() error {
	if v, ok := aluo.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.EntityType(); ok {
		if err := activitylog.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.entity_type": %w`, err)}
		}
	}
	if aluo.mutation.BoardCleared() && len(aluo.mutation.BoardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActivityLog.board"`)
	}
	return nil
}

func (aluo *ActivityLogUpdateOne) sqlSave(ctx context.Context) (_node *ActivityLog, err error) {
	if err := aluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitylog.Table, activitylog.Columns, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivityLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activitylog.FieldID)
		for _, f := range fields {
			if !activitylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activitylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := aluo.mutation.EntityType(); ok {
		_spec.SetField(activitylog.FieldEntityType, field.TypeString, value)
	}
	if aluo.mutation.EntityTypeCleared() {
		_spec.ClearField(activitylog.FieldEntityType, field.TypeString)
	}
	if value, ok := aluo.mutation.EntityID(); ok {
		_spec.SetField(activitylog.FieldEntityID, field.TypeUUID, value)
	}
	if aluo.mutation.EntityIDCleared() {
		_spec.ClearField(activitylog.FieldEntityID, field.TypeUUID)
	}
	if value, ok := aluo.mutation.OldValue(); ok {
		_spec.SetField(activitylog.FieldOldValue, field.TypeJSON, value)
	}
	if aluo.mutation.OldValueCleared() {
		_spec.ClearField(activitylog.FieldOldValue, field.TypeJSON)
	}
	if value, ok := aluo.mutation.NewValue(); ok {
		_spec.SetField(activitylog.FieldNewValue, field.TypeJSON, value)
	}
	if aluo.mutation.NewValueCleared() {
		_spec.ClearField(activitylog.FieldNewValue, field.TypeJSON)
	}
	if aluo.mutation.BoardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.BoardTable,
			Columns: []string{activitylog.BoardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.BoardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.BoardTable,
			Columns: []string{activitylog.BoardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivityLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
