// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/activitylog"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/board"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/list"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/predicate"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspace"
)

// BoardQuery is the builder for querying Board entities.
type BoardQuery struct {
	config
	ctx              *QueryContext
	order            []board.OrderOption
	inters           []Interceptor
	predicates       []predicate.Board
	withLists        *ListQuery
	withActivityLogs *ActivityLogQuery
	withWorkspace    *WorkspaceQuery
	withCreator      *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BoardQuery builder.
func (bq *BoardQuery) Where(ps ...predicate.Board) *BoardQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BoardQuery) Limit(limit int) *BoardQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BoardQuery) Offset(offset int) *BoardQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BoardQuery) Unique(unique bool) *BoardQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BoardQuery) Order(o ...board.OrderOption) *BoardQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryLists chains the current query on the "lists" edge.
func (bq *BoardQuery) QueryLists() *ListQuery {
	query := (&ListClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(board.Table, board.FieldID, selector),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, board.ListsTable, board.ListsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActivityLogs chains the current query on the "activity_logs" edge.
func (bq *BoardQuery) QueryActivityLogs() *ActivityLogQuery {
	query := (&ActivityLogClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(board.Table, board.FieldID, selector),
			sqlgraph.To(activitylog.Table, activitylog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, board.ActivityLogsTable, board.ActivityLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (bq *BoardQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(board.Table, board.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, board.WorkspaceTable, board.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreator chains the current query on the "creator" edge.
func (bq *BoardQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(board.Table, board.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, board.CreatorTable, board.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Board entity from the query.
// Returns a *NotFoundError when no Board was found.
func (bq *BoardQuery) First(ctx context.Context) (*Board, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{board.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BoardQuery) FirstX(ctx context.Context) *Board {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Board ID from the query.
// Returns a *NotFoundError when no Board ID was found.
func (bq *BoardQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{board.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BoardQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Board entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Board entity is found.
// Returns a *NotFoundError when no Board entities are found.
func (bq *BoardQuery) Only(ctx context.Context) (*Board, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{board.Label}
	default:
		return nil, &NotSingularError{board.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BoardQuery) OnlyX(ctx context.Context) *Board {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Board ID in the query.
// Returns a *NotSingularError when more than one Board ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BoardQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{board.Label}
	default:
		err = &NotSingularError{board.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BoardQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Boards.
func (bq *BoardQuery) All(ctx context.Context) ([]*Board, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryAll)
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Board, *BoardQuery]()
	return withInterceptors[[]*Board](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BoardQuery) AllX(ctx context.Context) []*Board {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Board IDs.
func (bq *BoardQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryIDs)
	if err = bq.Select(board.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BoardQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BoardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryCount)
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BoardQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BoardQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BoardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryExist)
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BoardQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BoardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BoardQuery) Clone() *BoardQuery {
	if bq == nil {
		return nil
	}
	return &BoardQuery{
		config:           bq.config,
		ctx:              bq.ctx.Clone(),
		order:            append([]board.OrderOption{}, bq.order...),
		inters:           append([]Interceptor{}, bq.inters...),
		predicates:       append([]predicate.Board{}, bq.predicates...),
		withLists:        bq.withLists.Clone(),
		withActivityLogs: bq.withActivityLogs.Clone(),
		withWorkspace:    bq.withWorkspace.Clone(),
		withCreator:      bq.withCreator.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithLists tells the query-builder to eager-load the nodes that are connected to
// the "lists" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoardQuery) WithLists(opts ...func(*ListQuery)) *BoardQuery {
	query := (&ListClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withLists = query
	return bq
}

// WithActivityLogs tells the query-builder to eager-load the nodes that are connected to
// the "activity_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoardQuery) WithActivityLogs(opts ...func(*ActivityLogQuery)) *BoardQuery {
	query := (&ActivityLogClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withActivityLogs = query
	return bq
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoardQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *BoardQuery {
	query := (&WorkspaceClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withWorkspace = query
	return bq
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoardQuery) WithCreator(opts ...func(*UserQuery)) *BoardQuery {
	query := (&UserClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withCreator = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Board.Query().
//		GroupBy(board.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BoardQuery) GroupBy(field string, fields ...string) *BoardGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BoardGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = board.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Board.Query().
//		Select(board.FieldName).
//		Scan(ctx, &v)
func (bq *BoardQuery) Select(fields ...string) *BoardSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BoardSelect{BoardQuery: bq}
	sbuild.label = board.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BoardSelect configured with the given aggregations.
func (bq *BoardQuery) Aggregate(fns ...AggregateFunc) *BoardSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BoardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !board.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BoardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Board, error) {
	var (
		nodes       = []*Board{}
		_spec       = bq.querySpec()
		loadedTypes = [4]bool{
			bq.withLists != nil,
			bq.withActivityLogs != nil,
			bq.withWorkspace != nil,
			bq.withCreator != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Board).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Board{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withLists; query != nil {
		if err := bq.loadLists(ctx, query, nodes,
			func(n *Board) { n.Edges.Lists = []*List{} },
			func(n *Board, e *List) { n.Edges.Lists = append(n.Edges.Lists, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withActivityLogs; query != nil {
		if err := bq.loadActivityLogs(ctx, query, nodes,
			func(n *Board) { n.Edges.ActivityLogs = []*ActivityLog{} },
			func(n *Board, e *ActivityLog) { n.Edges.ActivityLogs = append(n.Edges.ActivityLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withWorkspace; query != nil {
		if err := bq.loadWorkspace(ctx, query, nodes, nil,
			func(n *Board, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withCreator; query != nil {
		if err := bq.loadCreator(ctx, query, nodes, nil,
			func(n *Board, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BoardQuery) loadLists(ctx context.Context, query *ListQuery, nodes []*Board, init func(*Board), assign func(*Board, *List)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Board)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(list.FieldBoardID)
	}
	query.Where(predicate.List(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(board.ListsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BoardID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "board_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BoardQuery) loadActivityLogs(ctx context.Context, query *ActivityLogQuery, nodes []*Board, init func(*Board), assign func(*Board, *ActivityLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Board)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(activitylog.FieldBoardID)
	}
	query.Where(predicate.ActivityLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(board.ActivityLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BoardID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "board_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BoardQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*Board, init func(*Board), assign func(*Board, *Workspace)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Board)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BoardQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*Board, init func(*Board), assign func(*Board, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Board)
	for i := range nodes {
		fk := nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BoardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BoardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(board.Table, board.Columns, sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, board.FieldID)
		for i := range fields {
			if fields[i] != board.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bq.withWorkspace != nil {
			_spec.Node.AddColumnOnce(board.FieldWorkspaceID)
		}
		if bq.withCreator != nil {
			_spec.Node.AddColumnOnce(board.FieldCreatedBy)
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BoardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(board.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = board.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BoardGroupBy is the group-by builder for Board entities.
type BoardGroupBy struct {
	selector
	build *BoardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BoardGroupBy) Aggregate(fns ...AggregateFunc) *BoardGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BoardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, ent.OpQueryGroupBy)
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BoardQuery, *BoardGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BoardGroupBy) sqlScan(ctx context.Context, root *BoardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BoardSelect is the builder for selecting fields of Board entities.
type BoardSelect struct {
	*BoardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BoardSelect) Aggregate(fns ...AggregateFunc) *BoardSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BoardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, ent.OpQuerySelect)
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BoardQuery, *BoardSelect](ctx, bs.BoardQuery, bs, bs.inters, v)
}

func (bs *BoardSelect) sqlScan(ctx context.Context, root *BoardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
