// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/card"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/quicknote"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
)

// QuickNoteCreate is the builder for creating a QuickNote entity.
type QuickNoteCreate struct {
	config
	mutation *QuickNoteMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (qnc *QuickNoteCreate) SetContent(s string) *QuickNoteCreate {
	qnc.mutation.SetContent(s)
	return qnc
}

// SetCardID sets the "card_id" field.
func (qnc *QuickNoteCreate) SetCardID(u uuid.UUID) *QuickNoteCreate {
	qnc.mutation.SetCardID(u)
	return qnc
}

// SetCreatedBy sets the "created_by" field.
func (qnc *QuickNoteCreate) SetCreatedBy(u uuid.UUID) *QuickNoteCreate {
	qnc.mutation.SetCreatedBy(u)
	return qnc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (qnc *QuickNoteCreate) SetNillableCreatedBy(u *uuid.UUID) *QuickNoteCreate {
	if u != nil {
		qnc.SetCreatedBy(*u)
	}
	return qnc
}

// SetCreatedAt sets the "created_at" field.
func (qnc *QuickNoteCreate) SetCreatedAt(t time.Time) *QuickNoteCreate {
	qnc.mutation.SetCreatedAt(t)
	return qnc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qnc *QuickNoteCreate) SetNillableCreatedAt(t *time.Time) *QuickNoteCreate {
	if t != nil {
		qnc.SetCreatedAt(*t)
	}
	return qnc
}

// SetUpdatedAt sets the "updated_at" field.
func (qnc *QuickNoteCreate) SetUpdatedAt(t time.Time) *QuickNoteCreate {
	qnc.mutation.SetUpdatedAt(t)
	return qnc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qnc *QuickNoteCreate) SetNillableUpdatedAt(t *time.Time) *QuickNoteCreate {
	if t != nil {
		qnc.SetUpdatedAt(*t)
	}
	return qnc
}

// SetID sets the "id" field.
func (qnc *QuickNoteCreate) SetID(u uuid.UUID) *QuickNoteCreate {
	qnc.mutation.SetID(u)
	return qnc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (qnc *QuickNoteCreate) SetNillableID(u *uuid.UUID) *QuickNoteCreate {
	if u != nil {
		qnc.SetID(*u)
	}
	return qnc
}

// SetCard sets the "card" edge to the Card entity.
func (qnc *QuickNoteCreate) SetCard(c *Card) *QuickNoteCreate {
	return qnc.SetCardID(c.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (qnc *QuickNoteCreate) SetCreatorID(id uuid.UUID) *QuickNoteCreate {
	qnc.mutation.SetCreatorID(id)
	return qnc
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (qnc *QuickNoteCreate) SetNillableCreatorID(id *uuid.UUID) *QuickNoteCreate {
	if id != nil {
		qnc = qnc.SetCreatorID(*id)
	}
	return qnc
}

// SetCreator sets the "creator" edge to the User entity.
func (qnc *QuickNoteCreate) SetCreator(u *User) *QuickNoteCreate {
	return qnc.SetCreatorID(u.ID)
}

// Mutation returns the QuickNoteMutation object of the builder.
func (qnc *QuickNoteCreate) Mutation() *QuickNoteMutation {
	return qnc.mutation
}

// Save creates the QuickNote in the database.
func (qnc *QuickNoteCreate) Save(ctx context.Context) (*QuickNote, error) {
	qnc.defaults()
	return withHooks(ctx, qnc.sqlSave, qnc.mutation, qnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qnc *QuickNoteCreate) SaveX(ctx context.Context) *QuickNote {
	v, err := qnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qnc *QuickNoteCreate) Exec(ctx context.Context) error {
	_, err := qnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qnc *QuickNoteCreate) ExecX(ctx context.Context) {
	if err := qnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qnc *QuickNoteCreate) defaults() {
	if _, ok := qnc.mutation.CreatedAt(); !ok {
		v := quicknote.DefaultCreatedAt()
		qnc.mutation.SetCreatedAt(v)
	}
	if _, ok := qnc.mutation.UpdatedAt(); !ok {
		v := quicknote.DefaultUpdatedAt()
		qnc.mutation.SetUpdatedAt(v)
	}
	if _, ok := qnc.mutation.ID(); !ok {
		v := quicknote.DefaultID()
		qnc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qnc *QuickNoteCreate) check() error {
	if _, ok := qnc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "QuickNote.content"`)}
	}
	if v, ok := qnc.mutation.Content(); ok {
		if err := quicknote.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "QuickNote.content": %w`, err)}
		}
	}
	if _, ok := qnc.mutation.CardID(); !ok {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: missing required field "QuickNote.card_id"`)}
	}
	if _, ok := qnc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuickNote.created_at"`)}
	}
	if _, ok := qnc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuickNote.updated_at"`)}
	}
	if len(qnc.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "QuickNote.card"`)}
	}
	return nil
}

func (qnc *QuickNoteCreate) sqlSave(ctx context.Context) (*QuickNote, error) {
	if err := qnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	qnc.mutation.id = &_node.ID
	qnc.mutation.done = true
	return _node, nil
}

func (qnc *QuickNoteCreate) createSpec() (*QuickNote, *sqlgraph.CreateSpec) {
	var (
		_node = &QuickNote{config: qnc.config}
		_spec = sqlgraph.NewCreateSpec(quicknote.Table, sqlgraph.NewFieldSpec(quicknote.FieldID, field.TypeUUID))
	)
	if id, ok := qnc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := qnc.mutation.Content(); ok {
		_spec.SetField(quicknote.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := qnc.mutation.CreatedAt(); ok {
		_spec.SetField(quicknote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qnc.mutation.UpdatedAt(); ok {
		_spec.SetField(quicknote.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := qnc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quicknote.CardTable,
			Columns: []string{quicknote.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qnc.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quicknote.CreatorTable,
			Columns: []string{quicknote.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuickNoteCreateBulk is the builder for creating many QuickNote entities in bulk.
type QuickNoteCreateBulk struct {
	config
	err      error
	builders []*QuickNoteCreate
}

// Save creates the QuickNote entities in the database.
func (qncb *QuickNoteCreateBulk) Save(ctx context.Context) ([]*QuickNote, error) {
	if qncb.err != nil {
		return nil, qncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qncb.builders))
	nodes := make([]*QuickNote, len(qncb.builders))
	mutators := make([]Mutator, len(qncb.builders))
	for i := range qncb.builders {
		func(i int, root context.Context) {
			builder := qncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuickNoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qncb *QuickNoteCreateBulk) SaveX(ctx context.Context) []*QuickNote {
	v, err := qncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qncb *QuickNoteCreateBulk) Exec(ctx context.Context) error {
	_, err := qncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qncb *QuickNoteCreateBulk) ExecX(ctx context.Context) {
	if err := qncb.Exec(ctx); err != nil {
		panic(err)
	}
}
