// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/card"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/subtask"
)

// SubtaskCreate is the builder for creating a Subtask entity.
type SubtaskCreate struct {
	config
	mutation *SubtaskMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (sc *SubtaskCreate) SetTitle(s string) *SubtaskCreate {
	sc.mutation.SetTitle(s)
	return sc
}

// SetIsCompleted sets the "is_completed" field.
func (sc *SubtaskCreate) SetIsCompleted(b bool) *SubtaskCreate {
	sc.mutation.SetIsCompleted(b)
	return sc
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (sc *SubtaskCreate) SetNillableIsCompleted(b *bool) *SubtaskCreate {
	if b != nil {
		sc.SetIsCompleted(*b)
	}
	return sc
}

// SetPosition sets the "position" field.
func (sc *SubtaskCreate) SetPosition(i int) *SubtaskCreate {
	sc.mutation.SetPosition(i)
	return sc
}

// SetCardID sets the "card_id" field.
func (sc *SubtaskCreate) SetCardID(u uuid.UUID) *SubtaskCreate {
	sc.mutation.SetCardID(u)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SubtaskCreate) SetCreatedAt(t time.Time) *SubtaskCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SubtaskCreate) SetNillableCreatedAt(t *time.Time) *SubtaskCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SubtaskCreate) SetID(u uuid.UUID) *SubtaskCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *SubtaskCreate) SetNillableID(u *uuid.UUID) *SubtaskCreate {
	if u != nil {
		sc.SetID(*u)
	}
	return sc
}

// SetCard sets the "card" edge to the Card entity.
func (sc *SubtaskCreate) SetCard(c *Card) *SubtaskCreate {
	return sc.SetCardID(c.ID)
}

// Mutation returns the SubtaskMutation object of the builder.
func (sc *SubtaskCreate) Mutation() *SubtaskMutation {
	return sc.mutation
}

// Save creates the Subtask in the database.
func (sc *SubtaskCreate) Save(ctx context.Context) (*Subtask, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubtaskCreate) SaveX(ctx context.Context) *Subtask {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubtaskCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubtaskCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SubtaskCreate) defaults() {
	if _, ok := sc.mutation.IsCompleted(); !ok {
		v := subtask.DefaultIsCompleted
		sc.mutation.SetIsCompleted(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := subtask.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := subtask.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubtaskCreate) check() error {
	if _, ok := sc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Subtask.title"`)}
	}
	if v, ok := sc.mutation.Title(); ok {
		if err := subtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Subtask.title": %w`, err)}
		}
	}
	if _, ok := sc.mutation.IsCompleted(); !ok {
		return &ValidationError{Name: "is_completed", err: errors.New(`ent: missing required field "Subtask.is_completed"`)}
	}
	if _, ok := sc.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Subtask.position"`)}
	}
	if v, ok := sc.mutation.Position(); ok {
		if err := subtask.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "Subtask.position": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CardID(); !ok {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: missing required field "Subtask.card_id"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subtask.created_at"`)}
	}
	if len(sc.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "Subtask.card"`)}
	}
	return nil
}

func (sc *SubtaskCreate) sqlSave(ctx context.Context) (*Subtask, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubtaskCreate) createSpec() (*Subtask, *sqlgraph.CreateSpec) {
	var (
		_node = &Subtask{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subtask.Table, sqlgraph.NewFieldSpec(subtask.FieldID, field.TypeUUID))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.Title(); ok {
		_spec.SetField(subtask.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := sc.mutation.IsCompleted(); ok {
		_spec.SetField(subtask.FieldIsCompleted, field.TypeBool, value)
		_node.IsCompleted = value
	}
	if value, ok := sc.mutation.Position(); ok {
		_spec.SetField(subtask.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(subtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := sc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtask.CardTable,
			Columns: []string{subtask.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubtaskCreateBulk is the builder for creating many Subtask entities in bulk.
type SubtaskCreateBulk struct {
	config
	err      error
	builders []*SubtaskCreate
}

// Save creates the Subtask entities in the database.
func (scb *SubtaskCreateBulk) Save(ctx context.Context) ([]*Subtask, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subtask, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubtaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubtaskCreateBulk) SaveX(ctx context.Context) []*Subtask {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubtaskCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubtaskCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
