// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/card"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/subtask"
)

// Subtask is the model entity for the Subtask schema.
type Subtask struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// IsCompleted holds the value of the "is_completed" field.
	IsCompleted bool `json:"is_completed,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CardID holds the value of the "card_id" field.
	CardID uuid.UUID `json:"card_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubtaskQuery when eager-loading is set.
	Edges        SubtaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubtaskEdges holds the relations/edges for other nodes in the graph.
type SubtaskEdges struct {
	// Card holds the value of the card edge.
	Card *Card `json:"card,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubtaskEdges) CardOrErr() (*Card, error) {
	if e.Card != nil {
		return e.Card, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: card.Label}
	}
	return nil, &NotLoadedError{edge: "card"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subtask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subtask.FieldIsCompleted:
			values[i] = new(sql.NullBool)
		case subtask.FieldPosition:
			values[i] = new(sql.NullInt64)
		case subtask.FieldTitle:
			values[i] = new(sql.NullString)
		case subtask.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case subtask.FieldID, subtask.FieldCardID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subtask fields.
func (s *Subtask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subtask.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case subtask.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				s.Title = value.String
			}
		case subtask.FieldIsCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_completed", values[i])
			} else if value.Valid {
				s.IsCompleted = value.Bool
			}
		case subtask.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				s.Position = int(value.Int64)
			}
		case subtask.FieldCardID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field card_id", values[i])
			} else if value != nil {
				s.CardID = *value
			}
		case subtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subtask.
// This includes values selected through modifiers, order, etc.
func (s *Subtask) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryCard queries the "card" edge of the Subtask entity.
func (s *Subtask) QueryCard() *CardQuery {
	return NewSubtaskClient(s.config).QueryCard(s)
}

// Update returns a builder for updating this Subtask.
// Note that you need to call Subtask.Unwrap() before calling this method if this Subtask
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Subtask) Update() *SubtaskUpdateOne {
	return NewSubtaskClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Subtask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Subtask) Unwrap() *Subtask {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subtask is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Subtask) String() string {
	var builder strings.Builder
	builder.WriteString("Subtask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("title=")
	builder.WriteString(s.Title)
	builder.WriteString(", ")
	builder.WriteString("is_completed=")
	builder.WriteString(fmt.Sprintf("%v", s.IsCompleted))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", s.Position))
	builder.WriteString(", ")
	builder.WriteString("card_id=")
	builder.WriteString(fmt.Sprintf("%v", s.CardID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Subtasks is a parsable slice of Subtask.
type Subtasks []*Subtask
