// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/board"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/predicate"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspace"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspacemember"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wu *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WorkspaceUpdate) SetName(s string) *WorkspaceUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableName(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetDescription sets the "description" field.
func (wu *WorkspaceUpdate) SetDescription(s string) *WorkspaceUpdate {
	wu.mutation.SetDescription(s)
	return wu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableDescription(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetDescription(*s)
	}
	return wu
}

// ClearDescription clears the value of the "description" field.
func (wu *WorkspaceUpdate) ClearDescription() *WorkspaceUpdate {
	wu.mutation.ClearDescription()
	return wu
}

// SetThemeColor sets the "theme_color" field.
func (wu *WorkspaceUpdate) SetThemeColor(s string) *WorkspaceUpdate {
	wu.mutation.SetThemeColor(s)
	return wu
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableThemeColor(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetThemeColor(*s)
	}
	return wu
}

// SetCreatedBy sets the "created_by" field.
func (wu *WorkspaceUpdate) SetCreatedBy(u uuid.UUID) *WorkspaceUpdate {
	wu.mutation.SetCreatedBy(u)
	return wu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableCreatedBy(u *uuid.UUID) *WorkspaceUpdate {
	if u != nil {
		wu.SetCreatedBy(*u)
	}
	return wu
}

// ClearCreatedBy clears the value of the "created_by" field.
func (wu *WorkspaceUpdate) ClearCreatedBy() *WorkspaceUpdate {
	wu.mutation.ClearCreatedBy()
	return wu
}

// AddBoardIDs adds the "boards" edge to the Board entity by IDs.
func (wu *WorkspaceUpdate) AddBoardIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.AddBoardIDs(ids...)
	return wu
}

// AddBoards adds the "boards" edges to the Board entity.
func (wu *WorkspaceUpdate) AddBoards(b ...*Board) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return wu.AddBoardIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (wu *WorkspaceUpdate) AddMemberIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.AddMemberIDs(ids...)
	return wu
}

// AddMembers adds the "members" edges to the User entity.
func (wu *WorkspaceUpdate) AddMembers(u ...*User) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return wu.AddMemberIDs(ids...)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (wu *WorkspaceUpdate) SetCreatorID(id uuid.UUID) *WorkspaceUpdate {
	wu.mutation.SetCreatorID(id)
	return wu
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableCreatorID(id *uuid.UUID) *WorkspaceUpdate {
	if id != nil {
		wu = wu.SetCreatorID(*id)
	}
	return wu
}

// SetCreator sets the "creator" edge to the User entity.
func (wu *WorkspaceUpdate) SetCreator(u *User) *WorkspaceUpdate {
	return wu.SetCreatorID(u.ID)
}

// AddWorkspaceMembershipIDs adds the "workspace_memberships" edge to the WorkspaceMember entity by IDs.
func (wu *WorkspaceUpdate) AddWorkspaceMembershipIDs(ids ...int) *WorkspaceUpdate {
	wu.mutation.AddWorkspaceMembershipIDs(ids...)
	return wu
}

// AddWorkspaceMemberships adds the "workspace_memberships" edges to the WorkspaceMember entity.
func (wu *WorkspaceUpdate) AddWorkspaceMemberships(w ...*WorkspaceMember) *WorkspaceUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.AddWorkspaceMembershipIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wu *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return wu.mutation
}

// ClearBoards clears all "boards" edges to the Board entity.
func (wu *WorkspaceUpdate) ClearBoards() *WorkspaceUpdate {
	wu.mutation.ClearBoards()
	return wu
}

// RemoveBoardIDs removes the "boards" edge to Board entities by IDs.
func (wu *WorkspaceUpdate) RemoveBoardIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.RemoveBoardIDs(ids...)
	return wu
}

// RemoveBoards removes "boards" edges to Board entities.
func (wu *WorkspaceUpdate) RemoveBoards(b ...*Board) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return wu.RemoveBoardIDs(ids...)
}

// ClearMembers clears all "members" edges to the User entity.
func (wu *WorkspaceUpdate) ClearMembers() *WorkspaceUpdate {
	wu.mutation.ClearMembers()
	return wu
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (wu *WorkspaceUpdate) RemoveMemberIDs(ids ...uuid.UUID) *WorkspaceUpdate {
	wu.mutation.RemoveMemberIDs(ids...)
	return wu
}

// RemoveMembers removes "members" edges to User entities.
func (wu *WorkspaceUpdate) RemoveMembers(u ...*User) *WorkspaceUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return wu.RemoveMemberIDs(ids...)
}

// ClearCreator clears the "creator" edge to the User entity.
func (wu *WorkspaceUpdate) ClearCreator() *WorkspaceUpdate {
	wu.mutation.ClearCreator()
	return wu
}

// ClearWorkspaceMemberships clears all "workspace_memberships" edges to the WorkspaceMember entity.
func (wu *WorkspaceUpdate) ClearWorkspaceMemberships() *WorkspaceUpdate {
	wu.mutation.ClearWorkspaceMemberships()
	return wu
}

// RemoveWorkspaceMembershipIDs removes the "workspace_memberships" edge to WorkspaceMember entities by IDs.
func (wu *WorkspaceUpdate) RemoveWorkspaceMembershipIDs(ids ...int) *WorkspaceUpdate {
	wu.mutation.RemoveWorkspaceMembershipIDs(ids...)
	return wu
}

// RemoveWorkspaceMemberships removes "workspace_memberships" edges to WorkspaceMember entities.
func (wu *WorkspaceUpdate) RemoveWorkspaceMemberships(w ...*WorkspaceMember) *WorkspaceUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.RemoveWorkspaceMembershipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WorkspaceUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := wu.mutation.ThemeColor(); ok {
		if err := workspace.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Workspace.theme_color": %w`, err)}
		}
	}
	return nil
}

func (wu *WorkspaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeString, value)
	}
	if wu.mutation.DescriptionCleared() {
		_spec.ClearField(workspace.FieldDescription, field.TypeString)
	}
	if value, ok := wu.mutation.ThemeColor(); ok {
		_spec.SetField(workspace.FieldThemeColor, field.TypeString, value)
	}
	if wu.mutation.BoardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedBoardsIDs(); len(nodes) > 0 && !wu.mutation.BoardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.BoardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &WorkspaceMemberCreate{config: wu.config, mutation: newWorkspaceMemberMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedMembersIDs(); len(nodes) > 0 && !wu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkspaceMemberCreate{config: wu.config, mutation: newWorkspaceMemberMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkspaceMemberCreate{config: wu.config, mutation: newWorkspaceMemberMutation(wu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.CreatorTable,
			Columns: []string{workspace.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.CreatorTable,
			Columns: []string{workspace.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.WorkspaceMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedWorkspaceMembershipsIDs(); len(nodes) > 0 && !wu.mutation.WorkspaceMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.WorkspaceMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetName sets the "name" field.
func (wuo *WorkspaceUpdateOne) SetName(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableName(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetDescription sets the "description" field.
func (wuo *WorkspaceUpdateOne) SetDescription(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetDescription(s)
	return wuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableDescription(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetDescription(*s)
	}
	return wuo
}

// ClearDescription clears the value of the "description" field.
func (wuo *WorkspaceUpdateOne) ClearDescription() *WorkspaceUpdateOne {
	wuo.mutation.ClearDescription()
	return wuo
}

// SetThemeColor sets the "theme_color" field.
func (wuo *WorkspaceUpdateOne) SetThemeColor(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetThemeColor(s)
	return wuo
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableThemeColor(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetThemeColor(*s)
	}
	return wuo
}

// SetCreatedBy sets the "created_by" field.
func (wuo *WorkspaceUpdateOne) SetCreatedBy(u uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.SetCreatedBy(u)
	return wuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableCreatedBy(u *uuid.UUID) *WorkspaceUpdateOne {
	if u != nil {
		wuo.SetCreatedBy(*u)
	}
	return wuo
}

// ClearCreatedBy clears the value of the "created_by" field.
func (wuo *WorkspaceUpdateOne) ClearCreatedBy() *WorkspaceUpdateOne {
	wuo.mutation.ClearCreatedBy()
	return wuo
}

// AddBoardIDs adds the "boards" edge to the Board entity by IDs.
func (wuo *WorkspaceUpdateOne) AddBoardIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.AddBoardIDs(ids...)
	return wuo
}

// AddBoards adds the "boards" edges to the Board entity.
func (wuo *WorkspaceUpdateOne) AddBoards(b ...*Board) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return wuo.AddBoardIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (wuo *WorkspaceUpdateOne) AddMemberIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.AddMemberIDs(ids...)
	return wuo
}

// AddMembers adds the "members" edges to the User entity.
func (wuo *WorkspaceUpdateOne) AddMembers(u ...*User) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return wuo.AddMemberIDs(ids...)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (wuo *WorkspaceUpdateOne) SetCreatorID(id uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.SetCreatorID(id)
	return wuo
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableCreatorID(id *uuid.UUID) *WorkspaceUpdateOne {
	if id != nil {
		wuo = wuo.SetCreatorID(*id)
	}
	return wuo
}

// SetCreator sets the "creator" edge to the User entity.
func (wuo *WorkspaceUpdateOne) SetCreator(u *User) *WorkspaceUpdateOne {
	return wuo.SetCreatorID(u.ID)
}

// AddWorkspaceMembershipIDs adds the "workspace_memberships" edge to the WorkspaceMember entity by IDs.
func (wuo *WorkspaceUpdateOne) AddWorkspaceMembershipIDs(ids ...int) *WorkspaceUpdateOne {
	wuo.mutation.AddWorkspaceMembershipIDs(ids...)
	return wuo
}

// AddWorkspaceMemberships adds the "workspace_memberships" edges to the WorkspaceMember entity.
func (wuo *WorkspaceUpdateOne) AddWorkspaceMemberships(w ...*WorkspaceMember) *WorkspaceUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.AddWorkspaceMembershipIDs(ids...)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wuo *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return wuo.mutation
}

// ClearBoards clears all "boards" edges to the Board entity.
func (wuo *WorkspaceUpdateOne) ClearBoards() *WorkspaceUpdateOne {
	wuo.mutation.ClearBoards()
	return wuo
}

// RemoveBoardIDs removes the "boards" edge to Board entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveBoardIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.RemoveBoardIDs(ids...)
	return wuo
}

// RemoveBoards removes "boards" edges to Board entities.
func (wuo *WorkspaceUpdateOne) RemoveBoards(b ...*Board) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return wuo.RemoveBoardIDs(ids...)
}

// ClearMembers clears all "members" edges to the User entity.
func (wuo *WorkspaceUpdateOne) ClearMembers() *WorkspaceUpdateOne {
	wuo.mutation.ClearMembers()
	return wuo
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveMemberIDs(ids ...uuid.UUID) *WorkspaceUpdateOne {
	wuo.mutation.RemoveMemberIDs(ids...)
	return wuo
}

// RemoveMembers removes "members" edges to User entities.
func (wuo *WorkspaceUpdateOne) RemoveMembers(u ...*User) *WorkspaceUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return wuo.RemoveMemberIDs(ids...)
}

// ClearCreator clears the "creator" edge to the User entity.
func (wuo *WorkspaceUpdateOne) ClearCreator() *WorkspaceUpdateOne {
	wuo.mutation.ClearCreator()
	return wuo
}

// ClearWorkspaceMemberships clears all "workspace_memberships" edges to the WorkspaceMember entity.
func (wuo *WorkspaceUpdateOne) ClearWorkspaceMemberships() *WorkspaceUpdateOne {
	wuo.mutation.ClearWorkspaceMemberships()
	return wuo
}

// RemoveWorkspaceMembershipIDs removes the "workspace_memberships" edge to WorkspaceMember entities by IDs.
func (wuo *WorkspaceUpdateOne) RemoveWorkspaceMembershipIDs(ids ...int) *WorkspaceUpdateOne {
	wuo.mutation.RemoveWorkspaceMembershipIDs(ids...)
	return wuo
}

// RemoveWorkspaceMemberships removes "workspace_memberships" edges to WorkspaceMember entities.
func (wuo *WorkspaceUpdateOne) RemoveWorkspaceMemberships(w ...*WorkspaceMember) *WorkspaceUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.RemoveWorkspaceMembershipIDs(ids...)
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wuo *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workspace entity.
func (wuo *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WorkspaceUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.ThemeColor(); ok {
		if err := workspace.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Workspace.theme_color": %w`, err)}
		}
	}
	return nil
}

func (wuo *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Description(); ok {
		_spec.SetField(workspace.FieldDescription, field.TypeString, value)
	}
	if wuo.mutation.DescriptionCleared() {
		_spec.ClearField(workspace.FieldDescription, field.TypeString)
	}
	if value, ok := wuo.mutation.ThemeColor(); ok {
		_spec.SetField(workspace.FieldThemeColor, field.TypeString, value)
	}
	if wuo.mutation.BoardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedBoardsIDs(); len(nodes) > 0 && !wuo.mutation.BoardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.BoardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.BoardsTable,
			Columns: []string{workspace.BoardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &WorkspaceMemberCreate{config: wuo.config, mutation: newWorkspaceMemberMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedMembersIDs(); len(nodes) > 0 && !wuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkspaceMemberCreate{config: wuo.config, mutation: newWorkspaceMemberMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   workspace.MembersTable,
			Columns: workspace.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &WorkspaceMemberCreate{config: wuo.config, mutation: newWorkspaceMemberMutation(wuo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.CreatorTable,
			Columns: []string{workspace.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.CreatorTable,
			Columns: []string{workspace.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.WorkspaceMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedWorkspaceMembershipsIDs(); len(nodes) > 0 && !wuo.mutation.WorkspaceMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.WorkspaceMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workspace.WorkspaceMembershipsTable,
			Columns: []string{workspace.WorkspaceMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workspace{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
