// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/predicate"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspace"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspacemember"
)

// WorkspaceMemberUpdate is the builder for updating WorkspaceMember entities.
type WorkspaceMemberUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMemberMutation
}

// Where appends a list predicates to the WorkspaceMemberUpdate builder.
func (wmu *WorkspaceMemberUpdate) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberUpdate {
	wmu.mutation.Where(ps...)
	return wmu
}

// SetWorkspaceID sets the "workspace_id" field.
func (wmu *WorkspaceMemberUpdate) SetWorkspaceID(u uuid.UUID) *WorkspaceMemberUpdate {
	wmu.mutation.SetWorkspaceID(u)
	return wmu
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wmu *WorkspaceMemberUpdate) SetNillableWorkspaceID(u *uuid.UUID) *WorkspaceMemberUpdate {
	if u != nil {
		wmu.SetWorkspaceID(*u)
	}
	return wmu
}

// SetUserID sets the "user_id" field.
func (wmu *WorkspaceMemberUpdate) SetUserID(u uuid.UUID) *WorkspaceMemberUpdate {
	wmu.mutation.SetUserID(u)
	return wmu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wmu *WorkspaceMemberUpdate) SetNillableUserID(u *uuid.UUID) *WorkspaceMemberUpdate {
	if u != nil {
		wmu.SetUserID(*u)
	}
	return wmu
}

// SetRole sets the "role" field.
func (wmu *WorkspaceMemberUpdate) SetRole(w workspacemember.Role) *WorkspaceMemberUpdate {
	wmu.mutation.SetRole(w)
	return wmu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wmu *WorkspaceMemberUpdate) SetNillableRole(w *workspacemember.Role) *WorkspaceMemberUpdate {
	if w != nil {
		wmu.SetRole(*w)
	}
	return wmu
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (wmu *WorkspaceMemberUpdate) SetWorkspace(w *Workspace) *WorkspaceMemberUpdate {
	return wmu.SetWorkspaceID(w.ID)
}

// SetUser sets the "user" edge to the User entity.
func (wmu *WorkspaceMemberUpdate) SetUser(u *User) *WorkspaceMemberUpdate {
	return wmu.SetUserID(u.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (wmu *WorkspaceMemberUpdate) Mutation() *WorkspaceMemberMutation {
	return wmu.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (wmu *WorkspaceMemberUpdate) ClearWorkspace() *WorkspaceMemberUpdate {
	wmu.mutation.ClearWorkspace()
	return wmu
}

// ClearUser clears the "user" edge to the User entity.
func (wmu *WorkspaceMemberUpdate) ClearUser() *WorkspaceMemberUpdate {
	wmu.mutation.ClearUser()
	return wmu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wmu *WorkspaceMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wmu.sqlSave, wmu.mutation, wmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wmu *WorkspaceMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := wmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wmu *WorkspaceMemberUpdate) Exec(ctx context.Context) error {
	_, err := wmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmu *WorkspaceMemberUpdate) ExecX(ctx context.Context) {
	if err := wmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wmu *WorkspaceMemberUpdate) check() error {
	if v, ok := wmu.mutation.Role(); ok {
		if err := workspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "WorkspaceMember.role": %w`, err)}
		}
	}
	if wmu.mutation.WorkspaceCleared() && len(wmu.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.workspace"`)
	}
	if wmu.mutation.UserCleared() && len(wmu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.user"`)
	}
	return nil
}

func (wmu *WorkspaceMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacemember.Table, workspacemember.Columns, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt))
	if ps := wmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wmu.mutation.Role(); ok {
		_spec.SetField(workspacemember.FieldRole, field.TypeEnum, value)
	}
	if wmu.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wmu.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wmu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wmu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wmu.mutation.done = true
	return n, nil
}

// WorkspaceMemberUpdateOne is the builder for updating a single WorkspaceMember entity.
type WorkspaceMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMemberMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (wmuo *WorkspaceMemberUpdateOne) SetWorkspaceID(u uuid.UUID) *WorkspaceMemberUpdateOne {
	wmuo.mutation.SetWorkspaceID(u)
	return wmuo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wmuo *WorkspaceMemberUpdateOne) SetNillableWorkspaceID(u *uuid.UUID) *WorkspaceMemberUpdateOne {
	if u != nil {
		wmuo.SetWorkspaceID(*u)
	}
	return wmuo
}

// SetUserID sets the "user_id" field.
func (wmuo *WorkspaceMemberUpdateOne) SetUserID(u uuid.UUID) *WorkspaceMemberUpdateOne {
	wmuo.mutation.SetUserID(u)
	return wmuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wmuo *WorkspaceMemberUpdateOne) SetNillableUserID(u *uuid.UUID) *WorkspaceMemberUpdateOne {
	if u != nil {
		wmuo.SetUserID(*u)
	}
	return wmuo
}

// SetRole sets the "role" field.
func (wmuo *WorkspaceMemberUpdateOne) SetRole(w workspacemember.Role) *WorkspaceMemberUpdateOne {
	wmuo.mutation.SetRole(w)
	return wmuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wmuo *WorkspaceMemberUpdateOne) SetNillableRole(w *workspacemember.Role) *WorkspaceMemberUpdateOne {
	if w != nil {
		wmuo.SetRole(*w)
	}
	return wmuo
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (wmuo *WorkspaceMemberUpdateOne) SetWorkspace(w *Workspace) *WorkspaceMemberUpdateOne {
	return wmuo.SetWorkspaceID(w.ID)
}

// SetUser sets the "user" edge to the User entity.
func (wmuo *WorkspaceMemberUpdateOne) SetUser(u *User) *WorkspaceMemberUpdateOne {
	return wmuo.SetUserID(u.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (wmuo *WorkspaceMemberUpdateOne) Mutation() *WorkspaceMemberMutation {
	return wmuo.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (wmuo *WorkspaceMemberUpdateOne) ClearWorkspace() *WorkspaceMemberUpdateOne {
	wmuo.mutation.ClearWorkspace()
	return wmuo
}

// ClearUser clears the "user" edge to the User entity.
func (wmuo *WorkspaceMemberUpdateOne) ClearUser() *WorkspaceMemberUpdateOne {
	wmuo.mutation.ClearUser()
	return wmuo
}

// Where appends a list predicates to the WorkspaceMemberUpdate builder.
func (wmuo *WorkspaceMemberUpdateOne) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberUpdateOne {
	wmuo.mutation.Where(ps...)
	return wmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wmuo *WorkspaceMemberUpdateOne) Select(field string, fields ...string) *WorkspaceMemberUpdateOne {
	wmuo.fields = append([]string{field}, fields...)
	return wmuo
}

// Save executes the query and returns the updated WorkspaceMember entity.
func (wmuo *WorkspaceMemberUpdateOne) Save(ctx context.Context) (*WorkspaceMember, error) {
	return withHooks(ctx, wmuo.sqlSave, wmuo.mutation, wmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wmuo *WorkspaceMemberUpdateOne) SaveX(ctx context.Context) *WorkspaceMember {
	node, err := wmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wmuo *WorkspaceMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := wmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmuo *WorkspaceMemberUpdateOne) ExecX(ctx context.Context) {
	if err := wmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wmuo *WorkspaceMemberUpdateOne) check() error {
	if v, ok := wmuo.mutation.Role(); ok {
		if err := workspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "WorkspaceMember.role": %w`, err)}
		}
	}
	if wmuo.mutation.WorkspaceCleared() && len(wmuo.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.workspace"`)
	}
	if wmuo.mutation.UserCleared() && len(wmuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.user"`)
	}
	return nil
}

func (wmuo *WorkspaceMemberUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceMember, err error) {
	if err := wmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacemember.Table, workspacemember.Columns, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt))
	id, ok := wmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacemember.FieldID)
		for _, f := range fields {
			if !workspacemember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wmuo.mutation.Role(); ok {
		_spec.SetField(workspacemember.FieldRole, field.TypeEnum, value)
	}
	if wmuo.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wmuo.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wmuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wmuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkspaceMember{config: wmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wmuo.mutation.done = true
	return _node, nil
}
