// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/user"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspace"
	"github.com/tendo-mulira/tnotes-teams/internal/ent/workspacemember"
)

// WorkspaceMemberCreate is the builder for creating a WorkspaceMember entity.
type WorkspaceMemberCreate struct {
	config
	mutation *WorkspaceMemberMutation
	hooks    []Hook
}

// SetWorkspaceID sets the "workspace_id" field.
func (wmc *WorkspaceMemberCreate) SetWorkspaceID(u uuid.UUID) *WorkspaceMemberCreate {
	wmc.mutation.SetWorkspaceID(u)
	return wmc
}

// SetUserID sets the "user_id" field.
func (wmc *WorkspaceMemberCreate) SetUserID(u uuid.UUID) *WorkspaceMemberCreate {
	wmc.mutation.SetUserID(u)
	return wmc
}

// SetRole sets the "role" field.
func (wmc *WorkspaceMemberCreate) SetRole(w workspacemember.Role) *WorkspaceMemberCreate {
	wmc.mutation.SetRole(w)
	return wmc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wmc *WorkspaceMemberCreate) SetNillableRole(w *workspacemember.Role) *WorkspaceMemberCreate {
	if w != nil {
		wmc.SetRole(*w)
	}
	return wmc
}

// SetJoinedAt sets the "joined_at" field.
func (wmc *WorkspaceMemberCreate) SetJoinedAt(t time.Time) *WorkspaceMemberCreate {
	wmc.mutation.SetJoinedAt(t)
	return wmc
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (wmc *WorkspaceMemberCreate) SetNillableJoinedAt(t *time.Time) *WorkspaceMemberCreate {
	if t != nil {
		wmc.SetJoinedAt(*t)
	}
	return wmc
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (wmc *WorkspaceMemberCreate) SetWorkspace(w *Workspace) *WorkspaceMemberCreate {
	return wmc.SetWorkspaceID(w.ID)
}

// SetUser sets the "user" edge to the User entity.
func (wmc *WorkspaceMemberCreate) SetUser(u *User) *WorkspaceMemberCreate {
	return wmc.SetUserID(u.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (wmc *WorkspaceMemberCreate) Mutation() *WorkspaceMemberMutation {
	return wmc.mutation
}

// Save creates the WorkspaceMember in the database.
func (wmc *WorkspaceMemberCreate) Save(ctx context.Context) (*WorkspaceMember, error) {
	wmc.defaults()
	return withHooks(ctx, wmc.sqlSave, wmc.mutation, wmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wmc *WorkspaceMemberCreate) SaveX(ctx context.Context) *WorkspaceMember {
	v, err := wmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wmc *WorkspaceMemberCreate) Exec(ctx context.Context) error {
	_, err := wmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmc *WorkspaceMemberCreate) ExecX(ctx context.Context) {
	if err := wmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wmc *WorkspaceMemberCreate) defaults() {
	if _, ok := wmc.mutation.Role(); !ok {
		v := workspacemember.DefaultRole
		wmc.mutation.SetRole(v)
	}
	if _, ok := wmc.mutation.JoinedAt(); !ok {
		v := workspacemember.DefaultJoinedAt()
		wmc.mutation.SetJoinedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wmc *WorkspaceMemberCreate) check() error {
	if _, ok := wmc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceMember.workspace_id"`)}
	}
	if _, ok := wmc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WorkspaceMember.user_id"`)}
	}
	if _, ok := wmc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "WorkspaceMember.role"`)}
	}
	if v, ok := wmc.mutation.Role(); ok {
		if err := workspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "WorkspaceMember.role": %w`, err)}
		}
	}
	if _, ok := wmc.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "WorkspaceMember.joined_at"`)}
	}
	if len(wmc.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "WorkspaceMember.workspace"`)}
	}
	if len(wmc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WorkspaceMember.user"`)}
	}
	return nil
}

func (wmc *WorkspaceMemberCreate) sqlSave(ctx context.Context) (*WorkspaceMember, error) {
	if err := wmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	wmc.mutation.id = &_node.ID
	wmc.mutation.done = true
	return _node, nil
}

func (wmc *WorkspaceMemberCreate) createSpec() (*WorkspaceMember, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceMember{config: wmc.config}
		_spec = sqlgraph.NewCreateSpec(workspacemember.Table, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt))
	)
	if value, ok := wmc.mutation.Role(); ok {
		_spec.SetField(workspacemember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := wmc.mutation.JoinedAt(); ok {
		_spec.SetField(workspacemember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := wmc.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := wmc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkspaceMemberCreateBulk is the builder for creating many WorkspaceMember entities in bulk.
type WorkspaceMemberCreateBulk struct {
	config
	err      error
	builders []*WorkspaceMemberCreate
}

// Save creates the WorkspaceMember entities in the database.
func (wmcb *WorkspaceMemberCreateBulk) Save(ctx context.Context) ([]*WorkspaceMember, error) {
	if wmcb.err != nil {
		return nil, wmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wmcb.builders))
	nodes := make([]*WorkspaceMember, len(wmcb.builders))
	mutators := make([]Mutator, len(wmcb.builders))
	for i := range wmcb.builders {
		func(i int, root context.Context) {
			builder := wmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wmcb *WorkspaceMemberCreateBulk) SaveX(ctx context.Context) []*WorkspaceMember {
	v, err := wmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wmcb *WorkspaceMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := wmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmcb *WorkspaceMemberCreateBulk) ExecX(ctx context.Context) {
	if err := wmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
