// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCreatedWorkspaces holds the string denoting the created_workspaces edge name in mutations.
	EdgeCreatedWorkspaces = "created_workspaces"
	// EdgeCreatedBoards holds the string denoting the created_boards edge name in mutations.
	EdgeCreatedBoards = "created_boards"
	// EdgeCreatedCards holds the string denoting the created_cards edge name in mutations.
	EdgeCreatedCards = "created_cards"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeQuickNotes holds the string denoting the quick_notes edge name in mutations.
	EdgeQuickNotes = "quick_notes"
	// EdgeActivityLogs holds the string denoting the activity_logs edge name in mutations.
	EdgeActivityLogs = "activity_logs"
	// EdgeWorkspaces holds the string denoting the workspaces edge name in mutations.
	EdgeWorkspaces = "workspaces"
	// EdgeWorkspaceMemberships holds the string denoting the workspace_memberships edge name in mutations.
	EdgeWorkspaceMemberships = "workspace_memberships"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CreatedWorkspacesTable is the table that holds the created_workspaces relation/edge.
	CreatedWorkspacesTable = "workspaces"
	// CreatedWorkspacesInverseTable is the table name for the Workspace entity.
	// It exists in this package in order to avoid circular dependency with the "workspace" package.
	CreatedWorkspacesInverseTable = "workspaces"
	// CreatedWorkspacesColumn is the table column denoting the created_workspaces relation/edge.
	CreatedWorkspacesColumn = "created_by"
	// CreatedBoardsTable is the table that holds the created_boards relation/edge.
	CreatedBoardsTable = "boards"
	// CreatedBoardsInverseTable is the table name for the Board entity.
	// It exists in this package in order to avoid circular dependency with the "board" package.
	CreatedBoardsInverseTable = "boards"
	// CreatedBoardsColumn is the table column denoting the created_boards relation/edge.
	CreatedBoardsColumn = "created_by"
	// CreatedCardsTable is the table that holds the created_cards relation/edge.
	CreatedCardsTable = "cards"
	// CreatedCardsInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	CreatedCardsInverseTable = "cards"
	// CreatedCardsColumn is the table column denoting the created_cards relation/edge.
	CreatedCardsColumn = "created_by"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "user_id"
	// QuickNotesTable is the table that holds the quick_notes relation/edge.
	QuickNotesTable = "quick_notes"
	// QuickNotesInverseTable is the table name for the QuickNote entity.
	// It exists in this package in order to avoid circular dependency with the "quicknote" package.
	QuickNotesInverseTable = "quick_notes"
	// QuickNotesColumn is the table column denoting the quick_notes relation/edge.
	QuickNotesColumn = "created_by"
	// ActivityLogsTable is the table that holds the activity_logs relation/edge.
	ActivityLogsTable = "activity_logs"
	// ActivityLogsInverseTable is the table name for the ActivityLog entity.
	// It exists in this package in order to avoid circular dependency with the "activitylog" package.
	ActivityLogsInverseTable = "activity_logs"
	// ActivityLogsColumn is the table column denoting the activity_logs relation/edge.
	ActivityLogsColumn = "user_id"
	// WorkspacesTable is the table that holds the workspaces relation/edge. The primary key declared below.
	WorkspacesTable = "workspace_members"
	// WorkspacesInverseTable is the table name for the Workspace entity.
	// It exists in this package in order to avoid circular dependency with the "workspace" package.
	WorkspacesInverseTable = "workspaces"
	// WorkspaceMembershipsTable is the table that holds the workspace_memberships relation/edge.
	WorkspaceMembershipsTable = "workspace_members"
	// WorkspaceMembershipsInverseTable is the table name for the WorkspaceMember entity.
	// It exists in this package in order to avoid circular dependency with the "workspacemember" package.
	WorkspaceMembershipsInverseTable = "workspace_members"
	// WorkspaceMembershipsColumn is the table column denoting the workspace_memberships relation/edge.
	WorkspaceMembershipsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldUsername,
	FieldPasswordHash,
	FieldAvatarURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// WorkspacesPrimaryKey and WorkspacesColumn2 are the table columns denoting the
	// primary key for the workspaces relation (M2M).
	WorkspacesPrimaryKey = []string{"workspace_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	AvatarURLValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedWorkspacesCount orders the results by created_workspaces count.
func ByCreatedWorkspacesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedWorkspacesStep(), opts...)
	}
}

// ByCreatedWorkspaces orders the results by created_workspaces terms.
func ByCreatedWorkspaces(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedWorkspacesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedBoardsCount orders the results by created_boards count.
func ByCreatedBoardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedBoardsStep(), opts...)
	}
}

// ByCreatedBoards orders the results by created_boards terms.
func ByCreatedBoards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedBoardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedCardsCount orders the results by created_cards count.
func ByCreatedCardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedCardsStep(), opts...)
	}
}

// ByCreatedCards orders the results by created_cards terms.
func ByCreatedCards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedCardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuickNotesCount orders the results by quick_notes count.
func ByQuickNotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuickNotesStep(), opts...)
	}
}

// ByQuickNotes orders the results by quick_notes terms.
func ByQuickNotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuickNotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByActivityLogsCount orders the results by activity_logs count.
func ByActivityLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newActivityLogsStep(), opts...)
	}
}

// ByActivityLogs orders the results by activity_logs terms.
func ByActivityLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivityLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWorkspacesCount orders the results by workspaces count.
func ByWorkspacesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWorkspacesStep(), opts...)
	}
}

// ByWorkspaces orders the results by workspaces terms.
func ByWorkspaces(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkspacesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWorkspaceMembershipsCount orders the results by workspace_memberships count.
func ByWorkspaceMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWorkspaceMembershipsStep(), opts...)
	}
}

// ByWorkspaceMemberships orders the results by workspace_memberships terms.
func ByWorkspaceMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkspaceMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatedWorkspacesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedWorkspacesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedWorkspacesTable, CreatedWorkspacesColumn),
	)
}
func newCreatedBoardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedBoardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedBoardsTable, CreatedBoardsColumn),
	)
}
func newCreatedCardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedCardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedCardsTable, CreatedCardsColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newQuickNotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuickNotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuickNotesTable, QuickNotesColumn),
	)
}
func newActivityLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivityLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ActivityLogsTable, ActivityLogsColumn),
	)
}
func newWorkspacesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkspacesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, WorkspacesTable, WorkspacesPrimaryKey...),
	)
}
func newWorkspaceMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkspaceMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, WorkspaceMembershipsTable, WorkspaceMembershipsColumn),
	)
}
